### Import Libraries
##### In this section, the required libraries for data analysis and numerical operations are imported. Pandas is used for working with datasets, while NumPy is used for numerical calculations.

In [1]:
import pandas as pd
import numpy as np

### Load Dataset

##### In this section, the raw food delivery dataset is loaded into a Pandas DataFrame for further analysis.

In [2]:
df = pd.read_csv("train.csv")

### Preview Dataset

##### The first five rows of the dataset are displayed to preview the data and check its structure.

In [3]:
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,0x4607,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,19-03-2022,11:30:00,11:45:00,conditions Sunny,High,2,Snack,motorcycle,0,No,Urban,(min) 24
1,0xb379,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,25-03-2022,19:45:00,19:50:00,conditions Stormy,Jam,2,Snack,scooter,1,No,Metropolitian,(min) 33
2,0x5d6d,BANGRES19DEL01,23,4.4,12.914264,77.678400,12.924264,77.688400,19-03-2022,08:30:00,08:45:00,conditions Sandstorms,Low,0,Drinks,motorcycle,1,No,Urban,(min) 26
3,0x7a6a,COIMBRES13DEL02,38,4.7,11.003669,76.976494,11.053669,77.026494,05-04-2022,18:00:00,18:10:00,conditions Sunny,Medium,0,Buffet,motorcycle,1,No,Metropolitian,(min) 21
4,0x70a2,CHENRES12DEL01,32,4.6,12.972793,80.249982,13.012793,80.289982,26-03-2022,13:30:00,13:45:00,conditions Cloudy,High,1,Snack,scooter,1,No,Metropolitian,(min) 30

## Check Dataset Size

##### The shape of the dataset is checked to identify the number of rows and columns.

In [4]:
df.shape

(45593, 20)

### Check Column Names

##### The column names are displayed to understand the variables available in the dataset.

In [5]:
df.columns

Index(['ID', 'Delivery_person_ID', 'Delivery_person_Age',
       'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Order_Date', 'Time_Orderd',
       'Time_Order_picked', 'Weatherconditions', 'Road_traffic_density',
       'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle',
       'multiple_deliveries', 'Festival', 'City', 'Time_taken(min)'],
      dtype='object')

## Inspect Data Types

The dataset information is reviewed to check data types, the number of non-null values, and the overall structure of the dataset.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45593 entries, 0 to 45592
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45593 non-null  object
 1   Delivery_person_ID           45593 non-null  object
 2   Delivery_person_Age          45593 non-null  object
 3   Delivery_person_Ratings      45593 non-null  object
 4   Restaurant_latitude          45593 non-null  float64
 5   Restaurant_longitude         45593 non-null  float64
 6   Delivery_location_latitude   45593 non-null  float64
 7   Delivery_location_longitude  45593 non-null  float64
 8   Order_Date                   45593 non-null  object
 9   Time_Orderd                  45593 non-null  object
 10  Time_Order_picked            45593 non-null  object
 11  Weatherconditions            45593 non-null  object
 12  Road_traffic_density         45593 non-null  object
 13  Vehicle_condition            45593 non-null  int64
 14  Type_of_order                45593 non-null  object
 15  Type_of_vehicle              45593 non-null  object
 16  multiple_deliveries          45593 non-null  object
 17  Festival                     45593 non-null  object
 18  City                         45593 non-null  object
 19  Time_taken(min)              45593 non-null  object
dtypes: float64(4), int64(1), object(15)
memory usage: 7.0+ MB

## Check Missing Values

The number of missing values in each column is checked to identify incomplete data that may require cleaning.

In [7]:
df.isnull().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

## Inspect Age Values

The distribution of delivery person ages is reviewed, including missing values, to identify unusual or incomplete age data.

In [8]:
df['Delivery_person_Age'].value_counts(dropna=False)

Delivery_person_Age
35      2262
36      2260
37      2227
30      2226
38      2219
24      2210
32      2202
22      2196
29      2191
33      2187
28      2179
25      2174
34      2166
26      2159
21      2153
27      2150
39      2144
20      2136
31      2120
23      2087
NaN     1854
50        53
15        38
Name: count, dtype: int64

## Check Age Data Types

The data types of values in the delivery person age column are checked to identify inconsistent or unexpected formats.

In [9]:
df['Delivery_person_Age'].map(type).value_counts()

Delivery_person_Age
<class 'str'>    45593
Name: count, dtype: int64

## Check Textual Missing Values

Textual values representing missing data are checked in the delivery person age column before standardizing missing values.

In [10]:
df['Delivery_person_Age'].loc[
    df['Delivery_person_Age'].str.lower().str.strip() == 'nan'
].value_counts()

Delivery_person_Age
NaN     1854
Name: count, dtype: int64

## Inspect Rating Values

The distribution of delivery person ratings is reviewed, including missing values, to identify invalid or incomplete rating data.

In [11]:
df['Delivery_person_Ratings'].value_counts(dropna=False)

Delivery_person_Ratings
4.8     7148
4.7     7142
4.9     7041
4.6     6940
5       3996
4.5     3303
NaN     1908
4.1     1430
4.2     1418
4.3     1409
4.4     1361
4       1077
3.5      249
3.8      228
3.7      225
3.6      207
3.9      197
6         53
1         38
3.4       32
3.1       29
3.2       29
3.3       25
2.6       22
2.7       22
2.5       20
2.8       19
2.9       19
3          6
Name: count, dtype: int64

## Check Rating Data Types

The data types of values in the delivery person ratings column are checked to identify inconsistent or unexpected formats.

In [12]:
df['Delivery_person_Ratings'].map(type).value_counts()

Delivery_person_Ratings
<class 'str'>    45593
Name: count, dtype: int64

## Check Textual Missing Ratings

Textual values representing missing ratings are checked before converting them into standard missing values.

In [13]:
df['Delivery_person_Ratings'].loc[
    df['Delivery_person_Ratings'].str.lower().str.strip() == 'nan'
].value_counts()

Delivery_person_Ratings
NaN     1908
Name: count, dtype: int64

## Inspect Order Time

The distribution of order times is reviewed, including missing values, to identify incomplete or inconsistent time data.

In [14]:
df['Time_Orderd'].value_counts(dropna=False)

Time_Orderd
NaN         1731
21:55:00     461
17:55:00     456
20:00:00     449
22:20:00     448
            ...
12:25:00      57
14:15:00      56
16:00:00      53
13:20:00      52
16:30:00      51
Name: count, Length: 177, dtype: int64

## Check Order Time Data Types

The data types of values in the order time column are checked to identify inconsistent or unexpected formats.

In [15]:
df['Time_Orderd'].map(type).value_counts()

Time_Orderd
<class 'str'>    45593
Name: count, dtype: int64

## Check Textual Missing Order Times

Textual values representing missing order times are checked before converting them into standard missing values.

In [16]:
df['Time_Orderd'].loc[
    df['Time_Orderd'].str.lower().str.strip() == 'nan'
].value_counts()

Time_Orderd
NaN     1731
Name: count, dtype: int64

## Inspect Pickup Time

The distribution of order pickup times is reviewed, including missing values, to identify incomplete or inconsistent time data.

In [17]:
df['Time_Order_picked'].value_counts(dropna=False)

Time_Order_picked
21:30:00    496
22:50:00    474
22:40:00    458
18:40:00    457
17:55:00    456
           ...
15:10:00     48
16:15:00     46
16:10:00     43
17:10:00     39
16:20:00     38
Name: count, Length: 193, dtype: int64

## Check Pickup Time Data Types

The data types of values in the order pickup time column are checked to identify inconsistent or unexpected formats.

In [18]:
df['Time_Order_picked'].map(type).value_counts()

Time_Order_picked
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Multiple Deliveries

The distribution of multiple delivery values is reviewed, including missing values, to identify incomplete or inconsistent data.

In [19]:
df['multiple_deliveries'].value_counts(dropna=False)

multiple_deliveries
1       28159
0       14095
2        1985
NaN       993
3         361
Name: count, dtype: int64

## Check Multiple Deliveries Data Types

The data types of values in the multiple deliveries column are checked to identify inconsistent or unexpected formats.

In [20]:
df['multiple_deliveries'].map(type).value_counts()

multiple_deliveries
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Delivery Time

The distribution of delivery times is reviewed, including missing values, to understand the target variable before further analysis.

In [21]:
df['Time_taken(min)'].value_counts(dropna=False)

Time_taken(min)
(min) 26    2123
(min) 25    2050
(min) 27    1976
(min) 28    1965
(min) 29    1956
(min) 19    1824
(min) 15    1810
(min) 18    1765
(min) 16    1706
(min) 17    1696
(min) 24    1680
(min) 23    1643
(min) 20    1640
(min) 22    1626
(min) 21    1601
(min) 33    1259
(min) 30    1218
(min) 31    1213
(min) 34    1172
(min) 32    1124
(min) 38     887
(min) 36     852
(min) 39     847
(min) 35     832
(min) 37     828
(min) 11     757
(min) 10     750
(min) 12     746
(min) 14     739
(min) 13     716
(min) 43     567
(min) 42     561
(min) 40     555
(min) 41     553
(min) 44     553
(min) 47     295
(min) 49     280
(min) 48     277
(min) 46     274
(min) 45     241
(min) 53     100
(min) 51      94
(min) 54      91
(min) 52      79
(min) 50      72
Name: count, dtype: int64

## Check Delivery Time Data Types

The data types of values in the delivery time column are checked to ensure the variable has a consistent numeric format.

In [22]:
df['Time_taken(min)'].map(type).value_counts()

Time_taken(min)
<class 'str'>    45593
Name: count, dtype: int64

## Check Order Date Data Types

The data types of values in the order date column are checked to identify inconsistent or unexpected formats.

In [23]:
df['Order_Date'].map(type).value_counts()

Order_Date
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Order Dates

The distribution of order dates is reviewed, including missing values, to check the consistency and completeness of the date data.

In [24]:
df['Order_Date'].value_counts(dropna=False)

Order_Date
15-03-2022    1192
03-04-2022    1178
13-03-2022    1169
26-03-2022    1166
24-03-2022    1162
09-03-2022    1159
05-04-2022    1157
05-03-2022    1154
07-03-2022    1153
03-03-2022    1150
19-03-2022    1150
21-03-2022    1149
11-03-2022    1149
30-03-2022    1141
01-03-2022    1140
28-03-2022    1139
17-03-2022    1134
01-04-2022    1133
02-03-2022    1012
10-03-2022     996
16-03-2022     995
20-03-2022     994
02-04-2022     992
06-03-2022     986
04-03-2022     981
29-03-2022     977
25-03-2022     975
14-03-2022     974
11-02-2022     970
18-03-2022     968
31-03-2022     967
27-03-2022     965
12-03-2022     964
08-03-2022     964
23-03-2022     964
06-04-2022     961
13-02-2022     957
15-02-2022     945
04-04-2022     941
17-02-2022     939
12-02-2022     864
16-02-2022     861
18-02-2022     855
14-02-2022     851
Name: count, dtype: int64

## Check Weather Data Types

The data types of values in the weather conditions column are checked to identify inconsistent or unexpected formats.

In [25]:
df['Weatherconditions'].map(type).value_counts()

Weatherconditions
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Weather Conditions

The distribution of weather conditions is reviewed, including missing values, to identify incomplete or inconsistent data.

In [26]:
df['Weatherconditions'].value_counts(dropna=False)

Weatherconditions
conditions Fog           7654
conditions Stormy        7586
conditions Cloudy        7536
conditions Sandstorms    7495
conditions Windy         7422
conditions Sunny         7284
conditions NaN            616
Name: count, dtype: int64

## Check Textual Missing Weather Values

Textual values representing missing weather conditions are checked before standardizing them as missing values.

In [27]:
df['Weatherconditions'].loc[
    df['Weatherconditions'].str.lower().str.strip() == 'nan'
].value_counts()

Series([], Name: count, dtype: int64)

## Find NaN Text Variations

Values containing the text `"NaN"` are identified to detect different textual representations of missing weather conditions.

In [28]:
df['Weatherconditions'].loc[
    df['Weatherconditions'].str.contains('NaN', case=False, na=False)
].value_counts()

Weatherconditions
conditions NaN    616
Name: count, dtype: int64

## Check Traffic Density Data Types

The data types of values in the road traffic density column are checked to identify inconsistent or unexpected formats.

In [29]:
df['Road_traffic_density'].map(type).value_counts()

Road_traffic_density
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Traffic Density

The distribution of road traffic density is reviewed, including missing values, to identify incomplete or inconsistent data.

In [30]:
df['Road_traffic_density'].value_counts(dropna=False)

Road_traffic_density
Low        15477
Jam        14143
Medium     10947
High        4425
NaN          601
Name: count, dtype: int64

## Check Textual Missing Traffic Values

Textual values representing missing traffic density are checked before standardizing them as missing values.

In [31]:
df['Road_traffic_density'].loc[
    df['Road_traffic_density'].str.lower().str.strip() == 'nan'
].value_counts()

Road_traffic_density
NaN     601
Name: count, dtype: int64

## Check Vehicle Condition Data Types

The data types of values in the vehicle condition column are checked to identify inconsistent or unexpected formats.

In [32]:
df['Vehicle_condition'].map(type).value_counts()

Vehicle_condition
<class 'int'>    45593
Name: count, dtype: int64

## Inspect Vehicle Condition

The distribution of vehicle condition values is reviewed, including missing values, to identify incomplete or inconsistent data.

In [33]:
df['Vehicle_condition'].value_counts(dropna=False)

Vehicle_condition
2    15034
1    15030
0    15009
3      520
Name: count, dtype: int64

## Check Order Type Data Types

The data types of values in the order type column are checked to identify inconsistent or unexpected formats.

In [34]:
df['Type_of_order'].map(type).value_counts()

Type_of_order
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Order Types

The distribution of order types is reviewed, including missing values, to identify incomplete or inconsistent data.

df['Type_of_order'].value_counts(dropna=False)

## Check Vehicle Type Data Types

The data types of values in the vehicle type column are checked to identify inconsistent or unexpected formats.

In [35]:
df['Type_of_vehicle'].map(type).value_counts()

Type_of_vehicle
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Vehicle Types

The distribution of vehicle types is reviewed, including missing values, to identify incomplete or inconsistent data.

In [36]:
df['Type_of_vehicle'].value_counts(dropna=False)

Type_of_vehicle
motorcycle           26435
scooter              15276
electric_scooter      3814
bicycle                 68
Name: count, dtype: int64

## Check Multiple Deliveries Data Types

The data types of values in the multiple deliveries column are checked to identify inconsistent or unexpected formats.

In [37]:
df['multiple_deliveries'].map(type).value_counts()

multiple_deliveries
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Multiple Deliveries

The distribution of multiple delivery values is reviewed, including missing values, to identify incomplete or inconsistent data.

In [38]:
df['multiple_deliveries'].value_counts(dropna=False)

multiple_deliveries
1       28159
0       14095
2        1985
NaN       993
3         361
Name: count, dtype: int64

## Check Textual Missing Delivery Values

Textual values representing missing delivery information are checked before standardizing them as missing values.

In [39]:
df['multiple_deliveries'].loc[
    df['multiple_deliveries'].str.lower().str.strip() == 'nan'
].value_counts()

multiple_deliveries
NaN     993
Name: count, dtype: int64

## Check Festival Data Types

The data types of values in the festival column are checked to identify inconsistent or unexpected formats.

In [40]:
df['Festival'].map(type).value_counts()

Festival
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Festival Values

The distribution of festival values is reviewed, including missing values, to identify incomplete or inconsistent data.

In [41]:
df['Festival'].value_counts(dropna=False)

Festival
No      44469
Yes       896
NaN       228
Name: count, dtype: int64

## Check Textual Missing Festival Values

Textual values representing missing festival information are checked before standardizing them as missing values.

In [42]:
df['Festival'].loc[
    df['Festival'].str.lower().str.strip() == 'nan'
].value_counts()

Festival
NaN     228
Name: count, dtype: int64

## Check City Data Types

The data types of values in the city column are checked to identify inconsistent or unexpected formats.

In [43]:
df['City'].map(type).value_counts()

City
<class 'str'>    45593
Name: count, dtype: int64

## Inspect City Values

The distribution of city values is reviewed, including missing values, to identify incomplete or inconsistent data.

In [44]:
df['City'].value_counts(dropna=False)

City
Metropolitian     34093
Urban             10136
NaN                1200
Semi-Urban          164
Name: count, dtype: int64

## Check Textual Missing City Values

Textual values representing missing city information are checked before standardizing them as missing values.

In [45]:
df['City'].loc[
    df['City'].str.lower().str.strip() == 'nan'
].value_counts()

City
NaN     1200
Name: count, dtype: int64

## Check Delivery Time Data Types

The data types of values in the delivery time column are checked to ensure the variable has a consistent numeric format.

In [46]:
df['Time_taken(min)'].map(type).value_counts()

Time_taken(min)
<class 'str'>    45593
Name: count, dtype: int64

## Inspect Delivery Time Values

The distribution of delivery time values is reviewed, including missing values, to understand the target variable before further analysis.

In [47]:
df['Time_taken(min)'].value_counts(dropna=False)

Time_taken(min)
(min) 26    2123
(min) 25    2050
(min) 27    1976
(min) 28    1965
(min) 29    1956
(min) 19    1824
(min) 15    1810
(min) 18    1765
(min) 16    1706
(min) 17    1696
(min) 24    1680
(min) 23    1643
(min) 20    1640
(min) 22    1626
(min) 21    1601
(min) 33    1259
(min) 30    1218
(min) 31    1213
(min) 34    1172
(min) 32    1124
(min) 38     887
(min) 36     852
(min) 39     847
(min) 35     832
(min) 37     828
(min) 11     757
(min) 10     750
(min) 12     746
(min) 14     739
(min) 13     716
(min) 43     567
(min) 42     561
(min) 40     555
(min) 41     553
(min) 44     553
(min) 47     295
(min) 49     280
(min) 48     277
(min) 46     274
(min) 45     241
(min) 53     100
(min) 51      94
(min) 54      91
(min) 52      79
(min) 50      72
Name: count, dtype: int64

## Recheck Missing Values

The number of missing values in each column is rechecked after the initial data inspection.

In [48]:
df.isna().sum()

ID                             0
Delivery_person_ID             0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Date                     0
Time_Orderd                    0
Time_Order_picked              0
Weatherconditions              0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City                           0
Time_taken(min)                0
dtype: int64

## Check Missing Value Recognition

Pandas is used to check whether the string `"NaN"` is recognized as a missing value.

In [49]:
pd.isna("NaN")

False

## Check NumPy Missing Value

NumPy is used to verify whether `np.nan` is recognized as a missing value.

In [50]:
pd.isna(np.nan)

True

## Convert Column Names to List

The column names are converted into a Python list for easier access and manipulation.

In [51]:
df.columns.tolist()

['ID',
 'Delivery_person_ID',
 'Delivery_person_Age',
 'Delivery_person_Ratings',
 'Restaurant_latitude',
 'Restaurant_longitude',
 'Delivery_location_latitude',
 'Delivery_location_longitude',
 'Order_Date',
 'Time_Orderd',
 'Time_Order_picked',
 'Weatherconditions',
 'Road_traffic_density',
 'Vehicle_condition',
 'Type_of_order',
 'Type_of_vehicle',
 'multiple_deliveries',
 'Festival',
 'City',
 'Time_taken(min)']

## Create a Clean Data Copy

A copy of the original dataset is created for data cleaning while preserving the raw data.

In [52]:
df_clean = df.copy()

## Standardize Missing Values

Columns containing textual missing values are selected, and `"NaN"` strings are converted to standard NumPy missing values for consistent data cleaning.

In [53]:
cols_with_nan = [
    'Delivery_person_Age',
    'Delivery_person_Ratings',
    'Time_Orderd',
    'multiple_deliveries',
    'Road_traffic_density',
    'Festival',
    'City'
]

df_clean[cols_with_nan] = df_clean[cols_with_nan].replace('NaN', np.nan)

## Verify Missing Value Conversion

The selected columns are checked to verify that textual `"NaN"` values were successfully converted to standard missing values.

In [54]:
df_clean[cols_with_nan].isna().sum()

Delivery_person_Age        0
Delivery_person_Ratings    0
Time_Orderd                0
multiple_deliveries        0
Road_traffic_density       0
Festival                   0
City                       0
dtype: int64

## Verify Age Missing Values

The age column is checked to verify that textual `"NaN"` values have been successfully standardized as missing values.

In [55]:
df_clean['Delivery_person_Age'].loc[
    df_clean['Delivery_person_Age'].str.lower().str.strip() == 'nan'
].head()

42     NaN
74     NaN
120    NaN
140    NaN
179    NaN
Name: Delivery_person_Age, dtype: object

## Clean Age Text Values

Extra whitespace is removed from the values in the delivery person age column to ensure consistent formatting.

In [56]:
df_clean['Delivery_person_Age'] = df_clean['Delivery_person_Age'].str.strip()

## Convert Remaining Age Missing Values

Remaining textual `"NaN"` values in the delivery person age column are converted to standard NumPy missing values.

In [57]:
df_clean['Delivery_person_Age'] = df_clean['Delivery_person_Age'].replace('NaN', np.nan)

## Verify Age Missing Values

The number of missing values in the delivery person age column is checked after cleaning.

In [58]:
df_clean['Delivery_person_Age'].isna().sum()

1854

## Clean Missing Values Across Columns

Whitespace is removed and textual `"NaN"` values are standardized as missing values across the selected columns.

In [59]:
df_clean[cols_with_nan] = df_clean[cols_with_nan].apply(
    lambda col: col.str.strip().replace('NaN', np.nan)
)

## Verify Missing Values

The selected columns are checked to verify the final number of missing values after cleaning.

In [60]:
df_clean[cols_with_nan].isna().sum()

Delivery_person_Age        1854
Delivery_person_Ratings    1908
Time_Orderd                1731
multiple_deliveries         993
Road_traffic_density        601
Festival                    228
City                       1200
dtype: int64

## Clean Weather Conditions

The weather conditions column is standardized by removing extra text and whitespace and converting textual `"NaN"` values to missing values.

In [61]:
df_clean['Weatherconditions'] = (
    df_clean['Weatherconditions']
    .str.strip()
    .str.replace('conditions ', '', regex=False)
    .replace('NaN', np.nan)
)

## Verify Weather Missing Values

The number of missing values in the weather conditions column is checked after cleaning.

In [62]:
df_clean['Weatherconditions'].isna().sum()

616

## Convert Age to Numeric

The delivery person age column is converted to a numeric data type, with invalid values converted to missing values.

In [63]:
df_clean['Delivery_person_Age'] = pd.to_numeric(
    df_clean['Delivery_person_Age'],
    errors='coerce'
)

## Verify Age Data Type

The data type of the delivery person age column is checked after numeric conversion.

In [64]:
df_clean['Delivery_person_Age'].dtype

dtype('float64')

## Convert Numeric Columns

The ratings and multiple deliveries columns are converted to numeric data types, with invalid values converted to missing values.

In [65]:
df_clean['Delivery_person_Ratings'] = pd.to_numeric(
    df_clean['Delivery_person_Ratings'],
    errors='coerce'
)

df_clean['multiple_deliveries'] = pd.to_numeric(
    df_clean['multiple_deliveries'],
    errors='coerce'
)

## Verify Numeric Data Types

The data types of the ratings and multiple deliveries columns are checked after numeric conversion.

In [66]:
df_clean[['Delivery_person_Ratings', 'multiple_deliveries']].dtypes

Delivery_person_Ratings    float64
multiple_deliveries        float64
dtype: object

## Clean Delivery Time Values

The delivery time column is cleaned by removing the unnecessary `(min)` text from its values.

In [67]:
df_clean['Time_taken(min)'] = (
    df_clean['Time_taken(min)']
    .str.replace('(min) ', '', regex=False)
)

## Convert Delivery Time to Numeric

The delivery time column is converted to a numeric data type, with invalid values converted to missing values.

In [68]:
df_clean['Time_taken(min)'] = pd.to_numeric(
    df_clean['Time_taken(min)'],
    errors='coerce'
)

## Verify Delivery Time Data Type

The data type of the delivery time column is checked after numeric conversion.

In [69]:
df_clean['Time_taken(min)'].dtype

dtype('int64')

## Preview Order Dates

The first few values of the order date column are displayed to inspect the date format before conversion.

In [70]:
df_clean['Order_Date'].head()

0    19-03-2022
1    25-03-2022
2    19-03-2022
3    05-04-2022
4    26-03-2022
Name: Order_Date, dtype: object

## Convert Order Date

The order date column is converted to datetime format using the expected day-month-year pattern, with invalid values converted to missing values.

In [71]:
df_clean['Order_Date'] = pd.to_datetime(
    df_clean['Order_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)

## Verify Order Date Data Type

The data type of the order date column is checked after datetime conversion.

In [72]:
df_clean['Order_Date'].dtype

dtype('<M8[ns]')

## Preview Order and Pickup Times

The first ten values of the order and pickup time columns are displayed to inspect their formats before conversion.

In [73]:
df_clean[['Time_Orderd', 'Time_Order_picked']].head(10)

  Time_Orderd Time_Order_picked
0    11:30:00          11:45:00
1    19:45:00          19:50:00
2    08:30:00          08:45:00
3    18:00:00          18:10:00
4    13:30:00          13:45:00
5    21:20:00          21:30:00
6    19:15:00          19:30:00
7    17:25:00          17:30:00
8    20:55:00          21:05:00
9    21:55:00          22:10:00

## Convert Order Time

The order time column is converted to datetime format using the expected hour-minute-second pattern, with invalid values converted to missing values.

In [136]:
df_clean['Time_Orderd'] = pd.to_datetime(
    df_clean['Time_Orderd'],
    format='%H:%M:%S',
    errors='coerce'
)

## Verify Order Time Data Type

The data type of the order time column is checked after datetime conversion.

In [137]:
df_clean['Time_Orderd'].dtype

dtype('<M8[ns]')

## Convert Pickup Time

The order pickup time column is converted to datetime format using the expected hour-minute-second pattern, with invalid values converted to missing values.

In [138]:
df_clean['Time_Order_picked'] = pd.to_datetime(
    df_clean['Time_Order_picked'],
    format='%H:%M:%S',
    errors='coerce'
)

## Verify Pickup Time Data Type

The data type of the order pickup time column is checked after datetime conversion.

In [139]:
df_clean['Time_Order_picked'].dtype

dtype('<M8[ns]')

## Review Cleaned Data Structure

The structure, data types, and non-null counts of the cleaned dataset are reviewed to verify the results of the data cleaning process.

In [140]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45323 entries, 0 to 45592
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45323 non-null  object
 1   Delivery_person_ID           45323 non-null  object
 2   Delivery_person_Age          43486 non-null  float64
 3   Delivery_person_Ratings      43379 non-null  float64
 4   Restaurant_latitude          45323 non-null  float64
 5   Restaurant_longitude         45323 non-null  float64
 6   Delivery_location_latitude   45323 non-null  float64
 7   Delivery_location_longitude  45323 non-null  float64
 8   Order_Date                   45323 non-null  datetime64[ns]
 9   Time_Orderd                  43607 non-null  datetime64[ns]
 10  Time_Order_picked            45323 non-null  datetime64[ns]
 11  Weatherconditions            44712 non-null  object
 12  Road_traffic_density         44727 non-null  object
 13  Vehicle_condition            45323 non-null  int64
 14  Type_of_order                45323 non-null  object
 15  Type_of_vehicle              45323 non-null  object
 16  multiple_deliveries          44333 non-null  float64
 17  Festival                     45095 non-null  object
 18  City                         44125 non-null  object
 19  Time_taken(min)              45323 non-null  int64
 20  Prep Time                    43607 non-null  float64
 21  Order_Hour                   43607 non-null  float64
 22  Time_of_Day                  43177 non-null  object
 23  Delayed                      45323 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(9), int64(2), object(9)
memory usage: 8.3+ MB

## Verify Weather Conditions

The distribution of weather condition values is reviewed, including missing values, to verify the results of the cleaning process.

In [79]:
df_clean['Weatherconditions'].value_counts(dropna=False)

Weatherconditions
Fog           7654
Stormy        7586
Cloudy        7536
Sandstorms    7495
Windy         7422
Sunny         7284
NaN            616
Name: count, dtype: int64

## Verify Traffic Density

The distribution of road traffic density values is reviewed, including missing values, to verify the results of the cleaning process.

In [141]:
df_clean['Road_traffic_density'].value_counts(dropna=False)

Road_traffic_density
Low       15477
Jam       13902
Medium    10947
High       4401
NaN         596
Name: count, dtype: int64

## Verify Festival Values

The distribution of festival values is reviewed, including missing values, to verify the results of the cleaning process.

In [142]:
df_clean['Festival'].value_counts(dropna=False)

Festival
No     44291
Yes      804
NaN      228
Name: count, dtype: int64

## Verify City Values

The distribution of city values is reviewed, including missing values, to verify the results of the cleaning process.

In [143]:
df_clean['City'].value_counts(dropna=False)

City
Metropolitan    33902
Urban           10113
NaN              1198
Semi-Urban        110
Name: count, dtype: int64

## Correct City Name

The misspelled city value `Metropolitian` is corrected to `Metropolitan` for consistency.

In [144]:
df_clean['City'] = df_clean['City'].replace(
    'Metropolitian',
    'Metropolitan'
)

## Verify City Name Correction

The city value distribution is reviewed to verify that the misspelled city name has been corrected successfully.

In [145]:
df_clean['City'].value_counts(dropna=False)

City
Metropolitan    33902
Urban           10113
NaN              1198
Semi-Urban        110
Name: count, dtype: int64

## Review Cleaned Dataset

The cleaned dataset is reviewed to verify its structure, data types, and non-null values after the cleaning steps.

In [146]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45323 entries, 0 to 45592
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45323 non-null  object
 1   Delivery_person_ID           45323 non-null  object
 2   Delivery_person_Age          43486 non-null  float64
 3   Delivery_person_Ratings      43379 non-null  float64
 4   Restaurant_latitude          45323 non-null  float64
 5   Restaurant_longitude         45323 non-null  float64
 6   Delivery_location_latitude   45323 non-null  float64
 7   Delivery_location_longitude  45323 non-null  float64
 8   Order_Date                   45323 non-null  datetime64[ns]
 9   Time_Orderd                  43607 non-null  datetime64[ns]
 10  Time_Order_picked            45323 non-null  datetime64[ns]
 11  Weatherconditions            44712 non-null  object
 12  Road_traffic_density         44727 non-null  object
 13  Vehicle_condition            45323 non-null  int64
 14  Type_of_order                45323 non-null  object
 15  Type_of_vehicle              45323 non-null  object
 16  multiple_deliveries          44333 non-null  float64
 17  Festival                     45095 non-null  object
 18  City                         44125 non-null  object
 19  Time_taken(min)              45323 non-null  int64
 20  Prep Time                    43607 non-null  float64
 21  Order_Hour                   43607 non-null  float64
 22  Time_of_Day                  43177 non-null  object
 23  Delayed                      45323 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(9), int64(2), object(9)
memory usage: 8.3+ MB

## Calculate Preparation Time

Preparation time is calculated from the difference between order time and pickup time, then summarized to check its distribution.

In [147]:
prep_time_check = (
    df_clean['Time_Order_picked'] - df_clean['Time_Orderd']
).dt.total_seconds() / 60

prep_time_check.describe()

count    43607.000000
mean       -17.449951
std        196.680898
min      -1435.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
dtype: float64

## Check Negative Preparation Times

The number of negative preparation times is checked to identify cases where the pickup time occurs after midnight.

In [148]:
(prep_time_check < 0).sum()

831

## Inspect Negative Preparation Times

Examples of negative preparation times are displayed to identify cases where the pickup time occurs after midnight.

In [149]:
df_clean.loc[
    prep_time_check < 0,
    ['Time_Orderd', 'Time_Order_picked']
].head(10)

            Time_Orderd   Time_Order_picked
75  1900-01-01 23:50:00 1900-01-01 00:05:00
101 1900-01-01 23:55:00 1900-01-01 00:10:00
164 1900-01-01 23:50:00 1900-01-01 00:00:00
166 1900-01-01 23:45:00 1900-01-01 00:00:00
325 1900-01-01 23:55:00 1900-01-01 00:10:00
395 1900-01-01 23:55:00 1900-01-01 00:00:00
443 1900-01-01 23:45:00 1900-01-01 00:00:00
542 1900-01-01 23:45:00 1900-01-01 00:00:00
568 1900-01-01 23:55:00 1900-01-01 00:05:00
575 1900-01-01 23:50:00 1900-01-01 00:05:00

## Correct Midnight Crossover

Negative preparation times are adjusted by adding 24 hours to account for orders that cross midnight.

In [150]:
prep_time_check = prep_time_check.where(
    prep_time_check >= 0,
    prep_time_check + 24 * 60
)

## Verify Preparation Time

The preparation time distribution is reviewed again after correcting midnight crossover cases.

In [151]:
prep_time_check.describe()

count    43607.000000
mean         9.991515
std          4.086919
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
dtype: float64

## Add Preparation Time

The calculated preparation time is added to the cleaned dataset as a new column.

In [152]:
df_clean['Prep Time'] = prep_time_check

## Verify Preparation Time Column

The order time, pickup time, and preparation time are displayed together to verify the new calculated column.

In [153]:
df_clean[['Time_Orderd', 'Time_Order_picked', 'Prep Time']].head(10)

          Time_Orderd   Time_Order_picked  Prep Time
0 1900-01-01 11:30:00 1900-01-01 11:45:00       15.0
1 1900-01-01 19:45:00 1900-01-01 19:50:00        5.0
2 1900-01-01 08:30:00 1900-01-01 08:45:00       15.0
3 1900-01-01 18:00:00 1900-01-01 18:10:00       10.0
4 1900-01-01 13:30:00 1900-01-01 13:45:00       15.0
5 1900-01-01 21:20:00 1900-01-01 21:30:00       10.0
6 1900-01-01 19:15:00 1900-01-01 19:30:00       15.0
7 1900-01-01 17:25:00 1900-01-01 17:30:00        5.0
8 1900-01-01 20:55:00 1900-01-01 21:05:00       10.0
9 1900-01-01 21:55:00 1900-01-01 22:10:00       15.0

## Extract Order Hour

The hour is extracted from the order time to support time-based delivery performance analysis.

In [154]:
df_clean['Order_Hour'] = df_clean['Time_Orderd'].dt.hour

## Inspect Order Hour Distribution

The number of orders for each hour is reviewed in chronological order to understand the distribution of orders throughout the day.

In [155]:
df_clean['Order_Hour'].value_counts().sort_index()

Order_Hour
0.0      430
8.0     1818
9.0     1947
10.0    1991
11.0    1958
12.0     889
13.0     777
14.0     782
15.0     873
16.0     709
17.0    4278
18.0    4480
19.0    4528
20.0    4467
21.0    4598
22.0    4571
23.0    4511
Name: count, dtype: int64

## Create Time of Day Categories

Order hours are grouped into time-of-day categories to support analysis of delivery performance across different periods of the day.

In [156]:
conditions = [
    df_clean['Order_Hour'].between(8, 11),
    df_clean['Order_Hour'].between(12, 14),
    df_clean['Order_Hour'].between(15, 16),
    df_clean['Order_Hour'].between(17, 21),
    df_clean['Order_Hour'].between(22, 23)
]

choices = [
    'Morning',
    'Lunch Peak',
    'Afternoon',
    'Dinner Rush',
    'Night'
]

df_clean['Time_of_Day'] = np.select(
    conditions,
    choices,
    default=np.nan
)

## Check Dinner Rush Hours

The order hour is checked to identify orders placed during the dinner rush period.

In [157]:
df_clean['Order_Hour'].between(17, 21)

0        False
1         True
2        False
3         True
4        False
         ...
45588    False
45589     True
45590    False
45591    False
45592     True
Name: Order_Hour, Length: 45323, dtype: bool

## Verify Time of Day Categories

The distribution of orders across time-of-day categories is reviewed, including missing values, to verify the new classification.

In [158]:
df_clean['Time_of_Day'].value_counts(dropna=False)

Time_of_Day
Dinner Rush    22351
Night           9082
Morning         7714
Lunch Peak      2448
nan             2146
Afternoon       1582
Name: count, dtype: int64

## Verify Dinner Rush Range

The order hour is checked to verify which records fall within the defined dinner rush period.

In [159]:
df_clean['Order_Hour'].between(17, 21)

0        False
1         True
2        False
3         True
4        False
         ...
45588    False
45589     True
45590    False
45591    False
45592     True
Name: Order_Hour, Length: 45323, dtype: bool

## Create Time of Day Categories

Order hours are grouped into defined time-of-day categories to support analysis of delivery performance across different periods.

In [160]:
conditions = [
    df_clean['Order_Hour'].between(8, 11),
    df_clean['Order_Hour'].between(12, 14),
    df_clean['Order_Hour'].between(15, 16),
    df_clean['Order_Hour'].between(17, 21),
    df_clean['Order_Hour'].between(22, 23)
]

choices = [
    'Morning',
    'Lunch Peak',
    'Afternoon',
    'Dinner Rush',
    'Night'
]

df_clean['Time_of_Day'] = np.select(
    conditions,
    choices,
    default=np.nan
)

## Verify Time of Day Categories

The distribution of orders across time-of-day categories is reviewed, including missing values, to verify the classification.

In [161]:
df_clean['Time_of_Day'].value_counts(dropna=False)

Time_of_Day
Dinner Rush    22351
Night           9082
Morning         7714
Lunch Peak      2448
nan             2146
Afternoon       1582
Name: count, dtype: int64

## Compare Delivery and Preparation Time

Descriptive statistics for delivery time and preparation time are reviewed to compare their distributions and ranges.

In [162]:
df_clean[['Time_taken(min)', 'Prep Time']].describe()

       Time_taken(min)     Prep Time
count     45323.000000  43607.000000
mean         26.135251      9.991515
std           9.180874      4.086919
min          10.000000      5.000000
25%          19.000000      5.000000
50%          25.000000     10.000000
75%          32.000000     15.000000
max          51.000000     15.000000

## Remove Unreliable Transit Time

Transit time is not calculated because the dataset does not contain a delivery timestamp required to measure it reliably.

In [163]:
df_clean['Transit Time'] = (
    df_clean['Time_taken(min)'] - df_clean['Prep Time']
)

## Check Negative Transit Time Values

The number of negative values in the calculated transit-time field is checked as an intermediate validation step.

In [164]:
(df_clean['Transit Time'] < 0).sum()

1243

## Inspect Negative Transit Time Records

Examples of records with negative calculated transit times are displayed to inspect the intermediate calculation before excluding this unreliable measure.

In [165]:
df_clean.loc[
    df_clean['Transit Time'] < 0,
    ['Time_Orderd', 'Time_Order_picked', 'Prep Time', 'Time_taken(min)', 'Transit Time']
].head(10)

,Time_Orderd,Time_Order_picked,Prep Time,Time_taken(min),Transit Time
39,1900-01-01 08:40:00,1900-01-01 08:55:00,15.0,11,-4.0
75,1900-01-01 23:50:00,1900-01-01 00:05:00,15.0,10,-5.0
108,1900-01-01 10:55:00,1900-01-01 11:10:00,15.0,12,-3.0
199,1900-01-01 22:35:00,1900-01-01 22:50:00,15.0,11,-4.0
202,1900-01-01 10:30:00,1900-01-01 10:45:00,15.0,11,-4.0
242,1900-01-01 12:35:00,1900-01-01 12:50:00,15.0,14,-1.0
297,1900-01-01 22:25:00,1900-01-01 22:40:00,15.0,13,-2.0
421,1900-01-01 08:30:00,1900-01-01 08:45:00,15.0,12,-3.0
527,1900-01-01 22:20:00,1900-01-01 22:35:00,15.0,14,-1.0
578,1900-01-01 19:25:00,1900-01-01 19:40:00,15.0,11,-4.0

## Remove Transit Time

The unreliable transit-time column is removed because the dataset does not contain a delivery timestamp required for a valid transit-time calculation.

In [166]:
df_clean.drop(columns=['Transit Time'], inplace=True)

## Inspect Delivery Time Distribution

The delivery time values are reviewed in ascending order to understand their distribution before defining delayed orders.

In [167]:
df_clean['Time_taken(min)'].value_counts().sort_index()

Time_taken(min)
10     750
11     757
12     746
13     716
14     739
15    1810
16    1706
17    1696
18    1765
19    1824
20    1640
21    1601
22    1626
23    1643
24    1680
25    2050
26    2123
27    1976
28    1965
29    1956
30    1218
31    1213
32    1124
33    1259
34    1172
35     832
36     852
37     828
38     887
39     847
40     555
41     553
42     561
43     567
44     553
45     241
46     274
47     295
48     277
49     280
50      72
51      94
Name: count, dtype: int64

## Classify Delayed Orders

Orders with a delivery time above 30 minutes are classified as delayed for this analysis. This threshold is a project assumption because the dataset does not provide an official delay threshold.

In [168]:
df_clean['Delayed'] = (
    df_clean['Time_taken(min)'] > 30
)

## Verify Delayed Orders

The number of delayed and non-delayed orders is reviewed to verify the delay classification.

In [169]:
df_clean['Delayed'].value_counts()

Delayed
False    31987
True     13336
Name: count, dtype: int64

## Verify Outlier Removal

The number of delivery times above the calculated upper IQR bound is checked to verify that extreme outliers have been removed.

In [170]:
(df_clean['Time_taken(min)'] > 51.5).sum()

0

## Remove Delivery Time Outliers

Delivery records above the upper IQR bound of 51.5 minutes are removed to reduce the effect of extreme outliers on the analysis.

In [171]:
df_clean = df_clean[
    df_clean['Time_taken(min)'] <= 51.5
].copy()

## Verify Cleaned Dataset Size

The shape of the cleaned dataset is checked to verify the final number of records and columns after outlier removal.

In [172]:
df_clean.shape

(45323, 24)

## Review Final Dataset Structure

The cleaned dataset is reviewed to verify its structure, data types, and non-null values after the main data preparation steps.

In [173]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45323 entries, 0 to 45592
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45323 non-null  object
 1   Delivery_person_ID           45323 non-null  object
 2   Delivery_person_Age          43486 non-null  float64
 3   Delivery_person_Ratings      43379 non-null  float64
 4   Restaurant_latitude          45323 non-null  float64
 5   Restaurant_longitude         45323 non-null  float64
 6   Delivery_location_latitude   45323 non-null  float64
 7   Delivery_location_longitude  45323 non-null  float64
 8   Order_Date                   45323 non-null  datetime64[ns]
 9   Time_Orderd                  43607 non-null  datetime64[ns]
 10  Time_Order_picked            45323 non-null  datetime64[ns]
 11  Weatherconditions            44712 non-null  object
 12  Road_traffic_density         44727 non-null  object
 13  Vehicle_condition            45323 non-null  int64
 14  Type_of_order                45323 non-null  object
 15  Type_of_vehicle              45323 non-null  object
 16  multiple_deliveries          44333 non-null  float64
 17  Festival                     45095 non-null  object
 18  City                         44125 non-null  object
 19  Time_taken(min)              45323 non-null  int64
 20  Prep Time                    43607 non-null  float64
 21  Order_Hour                   43607 non-null  float64
 22  Time_of_Day                  45323 non-null  object
 23  Delayed                      45323 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(9), int64(2), object(9)
memory usage: 8.3+ MB

## Verify Final Time of Day Categories

The final distribution of time-of-day categories is reviewed, including missing values, to verify the feature after data cleaning.

In [174]:
df_clean['Time_of_Day'].value_counts(dropna=False)

Time_of_Day
Dinner Rush    22351
Night           9082
Morning         7714
Lunch Peak      2448
nan             2146
Afternoon       1582
Name: count, dtype: int64

## Standardize Time of Day Missing Values

Textual `"nan"` values in the time-of-day column are converted to standard missing values for consistent data handling.

In [175]:
df_clean['Time_of_Day'] = df_clean['Time_of_Day'].replace('nan', np.nan)

## Verify Time of Day Missing Values

The time-of-day categories are reviewed again, including missing values, to verify the final missing-value representation.

In [176]:
df_clean['Time_of_Day'].value_counts(dropna=False)

Time_of_Day
Dinner Rush    22351
Night           9082
Morning         7714
Lunch Peak      2448
NaN             2146
Afternoon       1582
Name: count, dtype: int64

## Review Final Missing Values

The number of missing values in each column is reviewed to assess the completeness of the cleaned dataset.

In [177]:
df_clean.isna().sum()

ID                                0
Delivery_person_ID                0
Delivery_person_Age            1837
Delivery_person_Ratings        1944
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1716
Time_Order_picked                 0
Weatherconditions               611
Road_traffic_density            596
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             990
Festival                        228
City                           1198
Time_taken(min)                   0
Prep Time                      1716
Order_Hour                     1716
Time_of_Day                    2146
Delayed                           0
dtype: int64

## Review Delivery Person Age

Descriptive statistics for delivery person age are reviewed to understand its distribution and range.

In [178]:
df_clean['Delivery_person_Age'].describe()

count    43486.000000
mean        29.551350
std          5.815995
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

## Review Delivery Person Ratings

Descriptive statistics for delivery person ratings are reviewed to understand their distribution and range.

In [179]:
df_clean['Delivery_person_Ratings'].describe()

count    43379.000000
mean         4.632954
std          0.331131
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

## Handle Invalid Ratings

Invalid rating values of 6 are converted to missing values because valid ratings are expected to fall within the 1–5 range.

In [180]:
df_clean.loc[
    df_clean['Delivery_person_Ratings'] == 6,
    'Delivery_person_Ratings'
] = np.nan

## Verify Cleaned Ratings

Descriptive statistics for delivery person ratings are reviewed after handling invalid values.

In [181]:
df_clean['Delivery_person_Ratings'].describe()

count    43379.000000
mean         4.632954
std          0.331131
min          1.000000
25%          4.500000
50%          4.700000
75%          4.900000
max          5.000000
Name: Delivery_person_Ratings, dtype: float64

## Inspect Multiple Deliveries

The distribution of multiple delivery values is reviewed, including missing values, in sorted order.

In [182]:
df_clean['multiple_deliveries'].value_counts(dropna=False).sort_index()

multiple_deliveries
0.0    14057
1.0    28044
2.0     1940
3.0      292
NaN      990
Name: count, dtype: int64

## Inspect Categorical Variables

The distributions of key categorical variables are reviewed, including missing values, to verify data consistency before analysis.

In [183]:
for col in [
    'Weatherconditions',
    'Road_traffic_density',
    'Festival',
    'City',
    'Type_of_order',
    'Type_of_vehicle'
]:
    print(f"\n--- {col} ---")
    print(df_clean[col].value_counts(dropna=False))

--- Weatherconditions ---
Weatherconditions
Fog           7597
Stormy        7549
Cloudy        7492
Sandstorms    7463
Windy         7378
Sunny         7233
NaN            611
Name: count, dtype: int64

--- Road_traffic_density ---
Road_traffic_density
Low       15477
Jam       13902
Medium    10947
High       4401
NaN         596
Name: count, dtype: int64

--- Festival ---
Festival
No     44291
Yes      804
NaN      228
Name: count, dtype: int64

--- City ---
City
Metropolitan    33902
Urban           10113
NaN              1198
Semi-Urban        110
Name: count, dtype: int64

--- Type_of_order ---
Type_of_order
Snack      11458
Meal       11393
Drinks     11262
Buffet     11210
Name: count, dtype: int64

--- Type_of_vehicle ---
Type_of_vehicle
motorcycle           26168
scooter              15274
electric_scooter      3813
bicycle                 68
Name: count, dtype: int64

## Review Final Dataset Structure

The dataset structure, data types, and non-null counts are reviewed to verify the final data preparation results.

In [184]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45323 entries, 0 to 45592
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           45323 non-null  object
 1   Delivery_person_ID           45323 non-null  object
 2   Delivery_person_Age          43486 non-null  float64
 3   Delivery_person_Ratings      43379 non-null  float64
 4   Restaurant_latitude          45323 non-null  float64
 5   Restaurant_longitude         45323 non-null  float64
 6   Delivery_location_latitude   45323 non-null  float64
 7   Delivery_location_longitude  45323 non-null  float64
 8   Order_Date                   45323 non-null  datetime64[ns]
 9   Time_Orderd                  43607 non-null  datetime64[ns]
 10  Time_Order_picked            45323 non-null  datetime64[ns]
 11  Weatherconditions            44712 non-null  object
 12  Road_traffic_density         44727 non-null  object
 13  Vehicle_condition            45323 non-null  int64
 14  Type_of_order                45323 non-null  object
 15  Type_of_vehicle              45323 non-null  object
 16  multiple_deliveries          44333 non-null  float64
 17  Festival                     45095 non-null  object
 18  City                         44125 non-null  object
 19  Time_taken(min)              45323 non-null  int64
 20  Prep Time                    43607 non-null  float64
 21  Order_Hour                   43607 non-null  float64
 22  Time_of_Day                  43177 non-null  object
 23  Delayed                      45323 non-null  bool
dtypes: bool(1), datetime64[ns](3), float64(9), int64(2), object(9)
memory usage: 8.3+ MB

## Export Cleaned Dataset

The cleaned dataset is exported to a CSV file for use in Tableau and further analysis.

In [186]:
df_clean.to_csv(
    'delivery_cleaned.csv',
    index=False
)

## Check Exported File Size

The size of the exported CSV file is checked to verify that the cleaned dataset was saved successfully.

In [187]:
import os

os.path.getsize('delivery_cleaned.csv')

9028860

## Verify Exported Dataset

The exported CSV file is loaded again and its shape is checked to verify that the saved dataset contains the expected number of rows and columns.

In [188]:
df_check = pd.read_csv('delivery_cleaned.csv')

df_check.shape

(45323, 24)

## Analyze Delivery Time by Time of Day

Average delivery time is calculated for each time-of-day category and sorted from highest to lowest.

In [189]:
df_clean.groupby('Time_of_Day')['Time_taken(min)'].mean().sort_values(ascending=False)

Time_of_Day
Dinner Rush    29.362445
Lunch Peak     27.080882
Afternoon      23.082174
Night          22.809403
Morning        21.259269
Name: Time_taken(min), dtype: float64

## Analyze Delivery Time by Traffic Density

Average delivery time is calculated for each traffic density level and sorted from highest to lowest.

In [190]:
df_clean.groupby('Road_traffic_density')['Time_taken(min)'].mean().sort_values(ascending=False)

Road_traffic_density
Jam       30.797439
High      27.099977
Medium    26.699644
Low       21.266977
Name: Time_taken(min), dtype: float64

## Analyze Delivery Time by Time and Traffic

Average delivery time is calculated for each combination of time-of-day and traffic density to identify potential operational bottlenecks.

In [191]:
df_clean.groupby(
    ['Time_of_Day', 'Road_traffic_density']
)['Time_taken(min)'].mean().round(2)

Time_of_Day  Road_traffic_density
Afternoon    High                    26.07
             Medium                  22.91
Dinner Rush  Jam                     30.77
             Medium                  27.34
Lunch Peak   High                    27.08
Morning      High                    27.11
             Low                     19.52
Night        Jam                     30.97
             Low                     22.43
Name: Time_taken(min), dtype: float64

## Analyze Delivery Time by Vehicle Type

Delivery time is compared across vehicle types using the mean, median, and number of orders to identify differences in delivery performance.

In [192]:
df_clean.groupby('Type_of_vehicle')['Time_taken(min)'].agg(
    ['mean', 'median', 'count']
).sort_values('mean', ascending=False).round(2)

                    mean  median  count
Type_of_vehicle
motorcycle         27.35    26.0  26168
bicycle            26.43    26.0     68
scooter            24.48    24.0  15274
electric_scooter   24.46    24.0   3813

## Analyze Delay Rate by Traffic Density

The delayed-order rate is calculated for each traffic density level and expressed as a percentage to compare delay patterns across traffic conditions.

In [194]:
df_clean.groupby('Road_traffic_density')['Delayed'].mean().mul(100).round(2).sort_values(ascending=False)

Road_traffic_density
Jam       49.78
High      33.20
Medium    32.47
Low        7.87
Name: Delayed, dtype: float64

## Analyze Delay Rate by Time and Traffic

The delayed-order rate is calculated for each combination of time-of-day and traffic density and expressed as a percentage.

In [195]:
df_clean.groupby(
    ['Time_of_Day', 'Road_traffic_density']
)['Delayed'].mean().mul(100).round(2)

Time_of_Day  Road_traffic_density
Afternoon    High                    31.40
             Medium                  14.44
Dinner Rush  Jam                     49.72
             Medium                  35.50
Lunch Peak   High                    33.13
Morning      High                    32.92
             Low                      2.13
Night        Jam                     50.38
             Low                     11.71
Name: Delayed, dtype: float64

## Summarize Delivery Performance

Order count, average delivery time, and delayed-order rate are calculated for each combination of time-of-day and traffic density.

In [196]:
df_clean.groupby(
    ['Time_of_Day', 'Road_traffic_density']
).agg(
    Orders=('ID', 'count'),
    Avg_Delivery_Time=('Time_taken(min)', 'mean'),
    Delayed_Rate=('Delayed', 'mean')
).assign(
    Delayed_Rate=lambda x: x['Delayed_Rate'] * 100
).round(2)

                                  Orders  Avg_Delivery_Time  Delayed_Rate
Time_of_Day Road_traffic_density
Afternoon   High                      86              26.07         31.40
            Medium                  1496              22.91         14.44
Dinner Rush Jam                    13169              30.77         49.72
            Medium                  9182              27.34         35.50
Lunch Peak  High                    2448              27.08         33.13
Morning     High                    1765              27.11         32.92
            Low                     5949              19.52          2.13
Night       Jam                      399              30.97         50.38
            Low                     8683              22.43         11.71